[package]
name = "tower-abci"
version = "0.1.0"
authors = ["Henry de Valence <hdevalence@hdevalence.ca>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tendermint-proto = { git = "https://github.com/informalsystems/tendermint-rs.git" }
tokio = { version = "1", features = ["full"]}
tower = { version = "0.4", features = ["full"]}